name: circuit-assistant-mobile-companion
options:
  bundleIdPrefix: org.circuitassistant.camc
  deploymentTarget:
    iOS: 14.0
fileGroups: [../../src]
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: Circuit Assistant Mobile Companion
      PRODUCT_BUNDLE_IDENTIFIER: org.circuitassistant.camc
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups: [app]
targets:
  circuit-assistant-mobile-companion_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: circuit-assistant-mobile-companion_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: circuit-assistant-mobile-companion_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64, metal]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 0.1.0
        CFBundleVersion: "0.1.0"
        UISupportsDocumentBrowser: true
        LSSupportsOpeningDocumentsInPlace: true
        UIFileSharingEnabled: true
        ITSAppUsesNonExemptEncryption: false
        UTImportedTypeDeclarations:
          - UTTypeConformsTo: [public.json, public.data]
            UTTypeDescription: JSON Document
            UTTypeIdentifier: public.json
            UTTypeTagSpecification:
              public.filename-extension: [json]
              public.mime-type: [application/json]
    entitlements:
      path: circuit-assistant-mobile-companion_iOS/circuit-assistant-mobile-companion_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ARCHS: [arm64]
        VALID_ARCHS: arm64 
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Externals
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups: [app]
    dependencies:
      - framework: libapp.a
        embed: false
      - framework: Externals/libapp.xcframework
        embed: false
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
    preBuildScripts:
      - script: |
          # If a prebuilt libapp.a exists for the current arch/configuration, skip the tauri xcode-script
          # This makes local simulator builds use the prebuilt static library instead of invoking the CLI helper
          CONFIG_LOWER=$(echo "${CONFIGURATION:-}" | tr '[:upper:]' '[:lower:]')
          CONFIG_UPPER=$(echo "${CONFIGURATION:-}" | tr '[:lower:]' '[:upper:]')

          CANDIDATES="$SRCROOT/Externals/libapp.xcframework $SRCROOT/Externals/arm64/${CONFIGURATION}/libapp.a $SRCROOT/Externals/arm64/${CONFIG_LOWER}/libapp.a $SRCROOT/Externals/arm64/${CONFIG_UPPER}/libapp.a $SRCROOT/Externals/x86_64/${CONFIGURATION}/libapp.a $SRCROOT/Externals/x86_64/${CONFIG_LOWER}/libapp.a $SRCROOT/Externals/x86_64/${CONFIG_UPPER}/libapp.a"

          for p in $CANDIDATES; do
            if [ -f "$p" ]; then
              echo "Found prebuilt libapp.a at $p — skipping tauri ios xcode-script"
              exit 0
            fi
          done

          # No prebuilt library found; fall back to invoking the tauri helper as before
          npm run -- tauri ios xcode-script -v --platform ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?} --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}" --header-search-paths "${HEADER_SEARCH_PATHS:?}" --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}" --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a