export const newCongregationObject = {
  number: '',
  name: '',
  branchOfficeCongregationName: '',
  city: '',
  cityNone: false,
  stateProvince: '',
  stateProvinceNone: false,
  country: '',
  venue: null,
  midweekMeetingDay: null,
  midweekMeetingTime: null,
  weekendMeetingDay: null,
  weekendMeetingTime: null,
  circuit: null,
  circuitSection: null,
  language: null,
  languageForms: null,
  group: false,
  hostCongregation: null,
  sponsorsGroup: false,
  prisonContact: false,
  participatesSMPW: false,
  // sponsoredGroupLanguages: false, // not needed at this time
  sponsorsPregroup: false,
  // sponsoredPregroupLanguages: false, // not needed at this time
  notes: '',
  branch: null,
  dataSource: null,
  sourceId: null,
  vCardUId: null,
  kmlData: '',
  jwOrgCongURL: ''
}
