export const newLetterObject = {
  letterName: '',
  letterDate: '',
  letterDateCentered: false,
  letterContent: '',
  letterRegarding: '',
  letterPathPDF: '',
  archived: false,
  externalLetter: false,
  includeLetterhead: true,
  letterHeadTemplateContent: '',
  letterHeadTemplateId: null,
  includeSignature: true,
  sentTo: [],
  sentCc: [],
  sentFrom: null,
  attention: '',
  letterSummary: '',
  letterPostscript: '',
  submitted: false,
  dateSubmitted: '',
  connectedToArray: [],
  hideTo: false,
  hideCc: false,
  attachmentsPaths: []
}
