export const newPQRObject = {
  personId: '', // from database
  submitted: false,
  nameWithBranch: '',
  datePQR: '',
  age: '',
  assignment: '',
  address: '',
  email: '',
  phone: '',
  citizen: '',
  languages: '',
  skills: '',
  hope: '',
  theoTraining: [],
  currentServing: [],
  currentServingOther: '',
  pastServicePriv: [],
  pastServiceOther: '',
  q10: '',
  q11: '',
  q12: '',
  q13: '',
  q14: '',
  q15: '',
  q16: '',
  q17: [],
  q17other: '',
  q18: '',
  q19: ''
}
