export const newPssObject = {
  studentsArray: [],
  students: [],
  classDate: null,
  serviceYear: null,
  confirmDate: null,
  language: null,
  classVenue: null,
  otherCoIsInstructorB: false,
  instructorB: null,
  altInstructorA: null,
  localElder: null,
  videoConferenceHost: null,
  deliveryMedium: 'co-located', // temporary default during COVID-19 'co-located',
  meetingId: null,
  meetingPassword: null,
  meetingURL: null,
  hostCongregation: null,
  bookPickupLocation: null,
  bookPickupDate: null,
  bookPickupTime: null,
  bookPickupCalendarSequence: 0,
  bookPickupCalendarUId: null,
  classNotes: null,
  includeWorkshopCal: false,
  hideConfirmations: false,
  hideBooks: false,
  prayerSchedule: [],
  prayerSchedulePath: null,
  prayerScheduleEmailSent: false,
  lastGradYearUpdated: false,
  rehearsalDateDefault: null,
  rehearsalTimeStartDefault: null,
  rehearsalTimeEndDefault: null,
  rehearsalVenueDefault: null
  // booksOrdered: false,
  // attendanceSubmitted: false
}
