export const newUserObject = {
  nameFirst: '',
  nameMiddle: '',
  nameLast: '',
  nameSuffix: null,
  nameNickname: null,
  wifeName: null,
  wifePhone: null,
  wifePhoto: null,
  addressHomeStreet: null,
  addressHomeApt: null,
  addressHomeCity: null,
  addressHomeStateProvince: null,
  addressHomePostal: null,
  phoneHome: null,
  phoneMobile: null,
  emailMain: null,
  emailMainPassword: null,
  emailJW: null,
  emailJWPubPassword: null,
  dateBirth: null,
  dateBaptism: null,
  hope: null,
  theoSchoolsGrad: null,
  personnelNumber: null,
  sceInstructor: false,
  sceInstructorFulltime: false,
  circuit: null,
  circuitNext: null,
  circuitNextEffectiveDate: null,
  s307sent: false,
  pdfFilePath307: '',
  photo: null,
  petAllergies: false,
  notes: '',
  brotherFollowingMe: '',
  brotherFollowed: '',
  licenseInfo: {}
  // pssBooksOnHand: null,
  // pssOrderURL: '',
  // pssOrderNotes: ''
}
